version: "3"

services:
  maradnode0:
    container_name: maradnode0
    image: "marad/node"
    ports:
      - "26657:26657"
      - "8545:8545"
      - "8546:8546"
      - "8125:8125"
    environment:
      - ID=0
      - LOG=${LOG:-marad.log}
    volumes:
      - ./localnet-setup/node0/marad:/mara:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  maradnode1:
    container_name: maradnode1
    image: "marad/node"
    ports:
      - "26658:26657"
      - "8555:8545"
      - "8556:8546"
      - "8126:8125"
    environment:
      - ID=1
      - LOG=${LOG:-marad.log}
    volumes:
      - ./localnet-setup/node1/marad:/mara:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  maradnode2:
    container_name: maradnode2
    image: "marad/node"
    environment:
      - ID=2
      - LOG=${LOG:-marad.log}
    ports:
      - "26659:26657"
      - "8565:8545"
      - "8566:8546"
      - "8127:8125"
    volumes:
      - ./localnet-setup/node2/marad:/mara:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

  maradnode3:
    container_name: maradnode3
    image: "marad/node"
    environment:
      - ID=3
      - LOG=${LOG:-marad.log}
    ports:
      - "26660:26657"
      - "8575:8545"
      - "8576:8546"
      - "8128:8125"
    volumes:
      - ./localnet-setup/node3/marad:/mara:Z
    networks:
      - localnet
    entrypoint: "bash start-docker.sh"

networks:
  localnet:
